(TeX-add-style-hook
 "tlride-book"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("jsfds" "submission")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("fontenc" "T1") ("inputenc" "utf8") ("geometry" "textwidth=6in" "textheight=8in")))
   (TeX-run-style-hooks
    "latex2e"
    "jsfds"
    "jsfds10"
    "hyperref"
    "amsmath"
    "amsthm"
    "natbib"
    "ifxetex"
    "ifluatex"
    "fixltx2e"
    "fontenc"
    "inputenc"
    "textcomp"
    "unicode-math"
    "upquote"
    "microtype"
    "parskip"
    "geometry"
    "color"
    "fancyvrb"
    "framed"
    "longtable"
    "booktabs"
    "footnote"
    "graphicx"
    "grffile"
    "amssymb"
    "tikz"
    "xcolor"
    "sectsty"
    "regexpatch"
    "letltxmacro"
    "makeidx"
    "fancyhdr")
   (TeX-add-symbols
    '("tcg" 1)
    '("gearmacro" 5)
    '("setchapterrulecolor" 1)
    '("WarningTok" 1)
    '("VerbatimStringTok" 1)
    '("VariableTok" 1)
    '("StringTok" 1)
    '("SpecialStringTok" 1)
    '("SpecialCharTok" 1)
    '("RegionMarkerTok" 1)
    '("PreprocessorTok" 1)
    '("OtherTok" 1)
    '("OperatorTok" 1)
    '("NormalTok" 1)
    '("KeywordTok" 1)
    '("InformationTok" 1)
    '("ImportTok" 1)
    '("FunctionTok" 1)
    '("FloatTok" 1)
    '("ExtensionTok" 1)
    '("ErrorTok" 1)
    '("DocumentationTok" 1)
    '("DecValTok" 1)
    '("DataTypeTok" 1)
    '("ControlFlowTok" 1)
    '("ConstantTok" 1)
    '("CommentVarTok" 1)
    '("CommentTok" 1)
    '("CharTok" 1)
    '("BuiltInTok" 1)
    '("BaseNTok" 1)
    '("AttributeTok" 1)
    '("AnnotationTok" 1)
    '("AlertTok" 1)
    "tightlist"
    "VerbBar"
    "VERB"
    "makegear"
    "gear"
    "stixdanger"
    "bbO"
    "bbD"
    "bbP"
    "bbR"
    "Algo"
    "Algora"
    "defq"
    "calF"
    "calM"
    "calP"
    "calO"
    "calQ"
    "Exp"
    "IC"
    "Gbar"
    "one"
    "psinos"
    "Phat"
    "Psihat"
    "Qbar"
    "maxwidth"
    "maxheight"
    "oldparagraph"
    "oldsubparagraph"
    "BeginKnitrBlock"
    "EndKnitrBlock")
   (LaTeX-add-labels
    "welcome"
    "part-on-the-road"
    "a-ride"
    "introduction"
    "causal-story"
    "tlrider-package"
    "discuss"
    "simulation-study"
    "reproducible-experiment"
    "synthetic-experiment"
    "revealing-experiment"
    "qw"
    "gbar"
    "qy"
    "qbar"
    "sample_from"
    "exo-visualization"
    "exo-make-own-experiment"
    "parameter"
    "parameter-first-pass"
    "definition"
    "eq:psi-zero"
    "causal-interpretation"
    "fig:DAG"
    "eq:psi-zero-bis"
    "causal-computation"
    "exo-alternative-parameter-first-pass"
    "eq:def-quantile"
    "eq:alter-gamma-zero"
    "eq:def-delta"
    "parameter-second-pass"
    "opening"
    "parameter-mapping"
    "eq:psimap"
    "value-another-experiment"
    "exo-alternative-parameter-second-pass"
    "parameter-third-pass"
    "yet-another"
    "eq:psi-zero-b"
    "eq:psi-zero-c"
    "rep-to-est"
    "exo-alternative-parameter-third-pass"
    "smooth"
    "smooth-first-pass"
    "fluctuations"
    "numerical-illus"
    "fig:psi-approx-psi-one"
    "exo-yet-another-experiment"
    "smooth-second-pass"
    "smooth-second-pass-fluctuations"
    "eq:fluct"
    "eq:score"
    "smoothness-and-gradients"
    "eq:derivative"
    "Euclidean-perspective"
    "canonical-gradient"
    "eq:eif"
    "fig:eic-three"
    "revisiting"
    "deriving-the-efficient-influence-curve"
    "eq:sigma0"
    "eq:slope-Pi"
    "numerical-validation"
    "influence-curves"
    "asymptotic-linearity"
    "eq:asymptotic-lin"
    "eq:asymp-lin"
    "influence-curves-and-gradients"
    "asymptotic-efficiency"
    "eq:CR"
    "exo-cramer-rao"
    "double-robustness"
    "linear-approximation"
    "from-gradients-to-estimators"
    "another-Euclidean-perspective"
    "the-remainder-term"
    "eq:taylor-expansion"
    "expressing-the-remainder-term-as-a-function-of-the-relevant-features"
    "eq:remainder-one"
    "eq:remainder"
    "exo-remainder-term"
    "def-double-robustness"
    "the-key-property"
    "eq:rem-two"
    "direct-consequence"
    "eq:solves-eic"
    "exo-double-robustness"
    "inference"
    "where-we-stand"
    "where-we-go"
    "simple-strategy"
    "a-cautionary-detour"
    "eq:cautionary"
    "delta-method"
    "eq:v-n-a"
    "known-gbar-first-pass"
    "a-simple-estimator"
    "eq:psi-n-b"
    "elementary-statistical-properties"
    "eq:v-n-b"
    "empirical-inves-IPTW"
    "fig:known-Gbar-one-b"
    "nuisance"
    "anatomy"
    "an-algorithmic-stance"
    "nuisance-QW"
    "fig:estimate-QW-two"
    "nuisance-Gbar"
    "logis-loss"
    "eq:logis-loss"
    "algo-Gbar-one"
    "fig:estimate-Gbar-three"
    "nuisance-Qbar-wm"
    "nuisance-Qbar"
    "qbar-machine-learning-based-algorithms"
    "Qbar-knn-algo"
    "boosted-trees"
    "fig:estimate-Qbar-five"
    "nuisance-Qbar-ml-exo"
    "naive-estimators"
    "why-naive"
    "known-gbar-second-pass"
    "unknown-gbar-constr"
    "elementary-stat-prop-iptw"
    "empirical-inves-IPTW-bis"
    "fig:unknown-Gbar-three"
    "fig:unknown-Gbar-four"
    "fig:unknown-Gbar-seven"
    "exo-a-nice-title"
    "Gcomp-estimator"
    "Gcomp-construction"
    "eq:Gcomp-estimator"
    "elementary-statistical-properties-1"
    "eq:var-Gcomp-n"
    "empirical-inves-Gcomp"
    "fig:estimating-Qbar-one-bis"
    "empirical-inves-Gcomp-varying"
    "fig:estimating-Qbar-four"
    "exo-plug-in-estimate"
    "one-step"
    "analysis-of-plug-in"
    "eq:hard-to-study"
    "eq:pre-one-step"
    "huber-one-step"
    "eq:def-one-step"
    "empirical-inves-one-step"
    "fig:one-step-one"
    "exo-one-step"
    "TMLE"
    "TMLE-motivations"
    "falling-outside-the-parameter-space"
    "eic-equation"
    "eq:solve"
    "eq:solve-approx"
    "basic-fact"
    "eq:solve-alt"
    "eq:solve-approx-alt"
    "targeted-fluctuation-TMLE"
    "fluctuating-indirectly"
    "eq:Qbarh"
    "fluct-direct"
    "eq:Q-fluct"
    "fig:fluctuation"
    "exo-fluct"
    "roaming"
    "eq:logis-loss-y"
    "fig:grid-search"
    "fluct-justification"
    "eq:fluct-score"
    "exo-tmle-flucs"
    "eq:Q-fluct-alt"
    "summary-and-perspectives"
    "empirical-inves-tmle"
    "empirical-inves-tmle-first"
    "exo-tmle"
    "fig:exo-tmle"
    "empirical-investigation"
    "fig:tmle"
    "closing-words"
    "notation"
    "proofs"
    "npsem"
    "identification"
    "prp:unnamed-chunk-2"
    "confidence-interval"
    "clt"
    "prp:unnamed-chunk-4"
    "order"
    "prp:unnamed-chunk-5"
    "another-rep"
    "prop-delta-method"
    "prp:unnamed-chunk-6"
    "oracle-logistic-risk"
    "eq:KL"
    "more-proofs"
    "estimation-of-the-asymptotic-variance-of-an-estimator"
    "iptw-est-var"
    "gcomp-est-var"
    "app-analysis-of-plug-in"
    "app-analysis-of-plug-in-main"
    "estimation-of-the-asymptotic-variance"
    "eq:bounded-sup-norm"
    "asymp-neglig-remain"
    "analysis-TMLE"
    "basic-eic-eq"
    "fluct-reg"
    "fluct-score"
    "eq:fluct-score-bis")
   (LaTeX-add-environments
    "Shaded"
    "theorem"
    "lemma"
    "corollary"
    "proposition"
    "conjecture"
    "definition"
    "example"
    "exercise")
   (LaTeX-add-bibliographies
    "bibliography.bib")
   (LaTeX-add-index-entries
    "identifiability"
    "algorithm"
    "nuisance~parameters|("
    "nuisance~parameters|)"
    "algorithm|("
    "algorithm!working~model|("
    "well/mis-specified"
    "algorithm!working~model|)"
    "algorithm!machine~learning|("
    "algorithm!cross-validation"
    "algorithm!machine~learning!stacking"
    "algorithm!machine~learning!super~learning"
    "algorithm!machine~learning|)"
    "algorithm|)"
    "nuisance~parameters"
    "conservative")
   (LaTeX-add-saveboxes
    "gearbox"))
 :latex)

